### ISSUE TITLE
unable to enable oe_content_event

### ISSUE THREAD

**Issue by john4190** [openeuropa/oe_corporate_countries#28]
i was trying to enable oe_content_event module but it fails and appears the folowing error message

Declaration of Drupal\oe_corporate_countries_address\Repository\CountryRepository::loadDefinitions($locale) must be compatible with Drupal\address\Repository\CountryRepository::loadDefinitions($locale): array in C:\xampp\htdocs\e3p2\web\modules\contrib\oe_corporate_countries\modules\oe_corporate_countries_address\src\Repository\CountryRepository.php on line 76

**Comment by brummbar** [comment]
Fixed in #26 .
